velodyne_vls_128:
  ros__parameters:
    lidar_name: "Velodyne VLS-32"
    vertical_channels: 32
    horizontal_resolution: 1024
    fov_bottom: -7
    fov_top: 52
    min_dist: 1.0
    max_dist: 120.0
